# Penny Ante Roulette Betting Rules Configuration
# This file defines payout ratios, betting limits, and casino rules

# Payout ratios for each bet type (amount won per unit bet, not including original bet)
payout_ratios:
  # Inside bets
  straight_up: 35        # Single number bet
  split: 17             # Two adjacent numbers
  street: 11            # Three numbers in a row
  corner: 8             # Four numbers in a square
  six_line: 5           # Six numbers in two adjacent rows
  
  # Outside bets
  red: 1                # All red numbers
  black: 1              # All black numbers
  odd: 1                # All odd numbers
  even: 1               # All even numbers
  high: 1               # Numbers 19-36
  low: 1                # Numbers 1-18
  first_dozen: 2        # Numbers 1-12
  second_dozen: 2       # Numbers 13-24
  third_dozen: 2        # Numbers 25-36
  first_column: 2       # First column
  second_column: 2      # Second column
  third_column: 2       # Third column

# Minimum bet amounts (in chips)
minimum_bets:
  global: 1             # Default minimum for all bets
  straight_up: 1        # Minimum for single number bets
  split: 1              # Minimum for split bets
  street: 1             # Minimum for street bets
  corner: 1             # Minimum for corner bets
  six_line: 1           # Minimum for six line bets
  red: 5                # Higher minimum for outside bets
  black: 5
  odd: 5
  even: 5
  high: 5
  low: 5
  first_dozen: 5
  second_dozen: 5
  third_dozen: 5
  first_column: 5
  second_column: 5
  third_column: 5

# Maximum bet amounts (as ratios of the table maximum bet)
maximum_bet_ratios:
  global: 1.0           # Default maximum ratio for all bets (100% of table max)
  straight_up: 0.5      # Lower maximum for high-payout bets (50% of table max)
  split: 0.75           # 75% of table max
  street: 0.85          # 85% of table max
  corner: 0.9           # 90% of table max
  six_line: 0.95        # 95% of table max
  red: 1.0              # Full maximum for outside bets (100% of table max)
  black: 1.0
  odd: 1.0
  even: 1.0
  high: 1.0
  low: 1.0
  first_dozen: 1.0
  second_dozen: 1.0
  third_dozen: 1.0
  first_column: 1.0
  second_column: 1.0
  third_column: 1.0

# House edge percentages for different bet types
house_edge:
  # American roulette house edges
  straight_up: 5.26
  split: 5.26
  street: 5.26
  corner: 5.26
  six_line: 5.26
  red: 5.26
  black: 5.26
  odd: 5.26
  even: 5.26
  high: 5.26
  low: 5.26
  first_dozen: 5.26
  second_dozen: 5.26
  third_dozen: 5.26
  first_column: 5.26
  second_column: 5.26
  third_column: 5.26

# Table-specific limits and rules
table_limits:
  AMERICAN:
    minimum_bet: 1              # Overall table minimum
    maximum_bet: 1000000        # Overall table maximum
    maximum_total_bet: 10000000 # Maximum total bet per spin
    wheel_spaces: 38            # Number of spaces on American wheel
    zero_spaces: ["0", "00"]    # Zero spaces on American wheel
    
  EUROPEAN:
    minimum_bet: 1              # Overall table minimum
    maximum_bet: 1000000        # Overall table maximum
    maximum_total_bet: 10000000 # Maximum total bet per spin
    wheel_spaces: 37            # Number of spaces on European wheel
    zero_spaces: ["0"]          # Zero spaces on European wheel

# Casino-specific rules (optional customizations)
casino_rules:
  allow_surrender: false        # "La Partage" or "En Prison" rules
  maximum_players: 8            # Maximum players per table
  betting_time_limit: 30        # Seconds allowed for betting
  minimum_chip_value: 1         # Minimum chip denomination
  maximum_chip_value: 100000    # Maximum chip denomination
  
# Special betting rules
special_rules:
  # Progressive betting limits (increases with consecutive wins)
  progressive_limits:
    enabled: false
    multiplier: 1.5
    max_progression: 5
    
  # Time-based limits
  session_limits:
    enabled: false
    max_session_time: 14400     # 4 hours in seconds
    max_session_loss: 1000000   # Maximum loss per session
    
  # VIP table settings
  vip_settings:
    enabled: false
    minimum_buy_in: 100000
    maximum_bet_multiplier: 10 